cloud-ms/app/models.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

from . import db
import datetime

class IdMixin(object):
    """ ID mixin
    """
    id = db.Column(db.Integer, primary_key=True)

class TimestampMixin(object):
    """ Timestamp mixin
    """
    created_at = db.Column(db.DateTime, default=datetime.datetime.now)
    # updated_at = db.Column(db.DateTime, default=datetime.datetime.now,
    #                        onupdate=datetime.datetime.now)


class Container(db.Model, IdMixin, TimestampMixin):
    __tablename__ = 'containers'
    container_id = db.Column(db.String(64), default='default')
    username = db.Column(db.String(64), default='default')
    container_name = db.Column(db.String(64), default='default')
    ports = db.Column(db.String(128), default='default')
    status = db.Column(db.String(64), default='default')

    def __repr__(self):
        return '<Container %r>' % self.container_name

cloud-ms/app/main/forms.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, Length

class CreateContainerForm(FlaskForm):
    username = StringField('username', validators=[DataRequired(), Length(1, 64)])
    containername = StringField('containername', validators=[DataRequired(), Length(1, 64)])

cloud-ms/app/__init__.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

from flask import Flask
from flask_bootstrap import Bootstrap
from config import config
import os, logging, logging.config
from flask_sqlalchemy import SQLAlchemy
from flask_wtf.csrf import CSRFProtect

csrf = CSRFProtect()
bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
	app = Flask(__name__)
	cfg = config[config_name]
	app.config.from_object(cfg)
	cfg.init_app(app)
	bootstrap.init_app(app)
	csrf.init_app(app)
	db.init_app(app)

	# init logging
	logging.config.fileConfig(app.config['LOG_CONFIG'])
	from .main import main as main_blueprint
	app.register_blueprint(main_blueprint)

	return app

app = create_app(os.environ.get('FLASK_CONFIG', 'default'))

cloud-ms/app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views

cloud-ms/app/main/views.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

from . import main
from flask import render_template, jsonify, request
from .forms import CreateContainerForm
import docker_tools
import logging
from .. import db
from ..models import Container

logger = logging.getLogger(__name__)

@main.route('/', methods=['GET'])
def index():
    containers = Container.query.all()
    return render_template('main/index.html', containers=containers)

@main.route('/operate_container', methods=['DELETE', 'POST'])
def operate_container():
    response = {
        'status': 'fail',
        'data': {}
    }
    if request.json:
        id = request.json.get('container_mid', None)
        operation_type = request.json.get('operation_type', None)
    else:
        operation_type = 'create'

    if operation_type == 'create':
        form = CreateContainerForm()
        if form.validate_on_submit():

            username = form.username.data
            container_name = form.containername.data

            # save container metadata in mysql，after success in creating container, update the container info in database
            container = Container()
            container.container_name = container_name
            container.username = username
            container.status = 'under creating'
            db.session.add(container)
            db.session.commit()

            logger.info("Create container %s" % container_name)

            # celery task
            docker_tools.operate_container.delay(container_mid=container.id, operation_type='create',
                                                 username=username,
                                                 container_name=container_name, image="cloud-ms/ubuntu:16.04",
                                                 mounts=[])

            response['status'] = 'success'
            response['data'] = {
                'container_name': container_name,
                'username': username
            }

    else:
        container = Container.query.filter_by(id=id).first()
        if container:
            container_id = container.container_id
            if operation_type:
                if operation_type == 'delete':
                    db.session.delete(container)
                    id=None
                elif operation_type == 'start':
                    container.status = 'under starting'
                    db.session.add(container)
                elif operation_type == 'stop':
                    container.status = 'under stopping'
                    db.session.add(container)
                docker_tools.operate_container.delay(container_mid=id, container_id=container_id, operation_type=operation_type)
            else:
                logger.error("You need to specify operation type!")

            response['data'] = {
                'container_name': container.container_name
            }
        else:
            logger.error("Container %d doesn't exist!" % id)
    return jsonify(response)

cloud-ms/app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block metas %}
    {{ super() }}
    <meta name="csrf-token" content="{{ csrf_token() }}">
{% endblock metas %}

{% block styles %}
    {{ super() }}
    {% block inline_styles %}{% endblock %}
    {% block plugin_styles %}{% endblock %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
    // csrf protect
    var csrftoken = $('meta[name=csrf-token]').attr('content');
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken)
            }
        }
    });
    </script>
    {% block inline_scripts %}{% endblock %}
    {% block plugin_scripts %}{% endblock  %}
{% endblock %}

cloud-ms/app/templates/main/index.html
{% extends 'base.html' %}
{% block title %}容器云管理系统{% endblock %}

{% block plugin_styles %}
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/datatables.min.css') }}">
{% endblock %}

{% block inline_styles %}
    <style type="text/css">
        .middle {
            text-align: center;
            margin: auto;
            width: 70%;
        }
        #content-header {
            margin: 20px;
        }
        a {
            cursor: pointer;
        }
        #pd {
            text-align: right;
            margin: 20px;
        }
        .input-addon {
            width: 120px;
        }
        .input-group {
            margin-bottom: 5px;
        }
        .error {
            color: red;
        }
        .operetion {
            padding-left: 4px;
        }
    </style>

{% endblock %}

{% block content %}
    <div class="middle">
        <div id="content-header">
            <h1>容器云管理系统</h1>
        </div>
        <div id="content-body">
            <div id="pd">
                <a id="create_container">创建容器</a>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <table id="containers_table" class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>container-name</th>
                            <th>username</th>
                            <th>ports</th>
                            <th>status</th>
                            <th>operations</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for container in containers %}
                            <tr id="{{ container.id }}">
                                <td>
                                    {{ container.container_name }}
                                </td>
                                <td>
                                    {{ container.username }}
                                </td>
                                <td>
                                    {{ container.ports }}
                                </td>
                                <td>
                                    {{ container.status }}
                                </td>
                                <td>
                                    <a onclick="operate_container({{ container.id }}, '{{ container.container_name }}',
                                            'delete')"><span class="operetion glyphicon glyphicon-trash"
                                                             aria-hidden="true" style="color: #cc6363"></span></a>
                                    <a onclick="operate_container({{ container.id }},
                                            '{{ container.container_name }}', 'stop')">
                                        <span class="operetion glyphicon glyphicon-stop"
                                              aria-hidden="true" style="color: #675252"></span></a>
                                    <a onclick="operate_container({{ container.id }},
                                            '{{ container.container_name }}', 'start')">
                                        <span class="operetion glyphicon glyphicon-play" aria-hidden="true"></span></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <div class="modal fade" id="create_container_modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close" \
                        ><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Create Container</h4>
                </div>
                <div class="modal-body">
                    <form id="container-form">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <div class="input-group">
                            <span class="input-group-addon"><div class="input-addon">Username</div></span>
                            <input id="username" type="text" name='username' class="form-control" \
                                   placeholder="Username" required \
                                   data-msg-required='Please input the username!'>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon"><div class="input-addon" \
                            >Container-name</div></span>
                            <input id="containername" name="containername" type="text" \
                                   class="form-control" placeholder="Container name" \
                                   required data-msg-required='Please input the container name!'>
                        </div>
                    </form>
                 </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" id="save_create_container">Save</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="operations_modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close" \
                        ><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                 </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" id="confirm_operation">Confirm</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block plugin_scripts %}
<script src="{{ url_for('static', filename='js/jquery.validate.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/datatables.min.js') }}"></script>
{% endblock  %}

{% block inline_scripts %}
    <script type="text/javascript">
    var containerId;
    var operationType;
    var DELETE = 'delete';
    var STOP = 'stop';
    var START = 'start';
    $(function () {
        var containers_table = $("#containers_table").DataTable({
                "aoColumns": [
                    null, null, null, null, null
                ],
                "aaSorting": []
            });
        $("#create_container").click(function () {
            $("#create_container_modal").modal("show");
        });
        $("#container-form").validate({
            errorPlacement: function (error, element) {
                element.parents(".input-group").after(error);
            }
        });
        $('#save_create_container').click(function () {
            if ($("#container-form").valid()) {
                $.ajax({
                    url: "{{ url_for('main.operate_container') }}",
                    type: "post",
                    data: $("#container-form").serialize(),
                    success: function(data) {
                        $("#create_container_modal").modal("hide");
                        $("#container-form")[0].reset();
                        window.location.reload();
                    }
                });
            } else {
                return;
            }
        });
        $('#confirm_operation').click(function () {
            if (operationType == DELETE) {
                type='delete';
            } else {
                type = 'post';
            }
            $.ajax({
                    url: "{{ url_for('main.operate_container') }}",
                    type: type,
                    data: JSON.stringify({'container_mid': containerId, 'operation_type': operationType}),
                    contentType: "application/json",
                    success: function(data) {
                        $("#operations_modal").modal("hide");
                        window.location.reload();
                    }
                });
        });
    });
    function operate_container(contain_id, container_name, operation) {
        containerId = contain_id;
        operationType = operation;
        if (operation == DELETE) {
            title = 'Delete Container';
            body = 'Are you sure to delete the container: ' + container_name + '?';
        } else if (operation == STOP) {
            title = 'Stop Container';
            body = 'Are you sure to stop the container: ' + container_name + '?';
        } else if (operation == START) {
            title = 'Start Container';
            body = 'Are you sure to start the container: ' + container_name + '?';
        }
        $("#operations_modal").find(".modal-title").text(title);
        $("#operations_modal").find(".modal-body").text(body);
        $("#operations_modal").modal("show");
    }
    </script>
{% endblock %}